version: '2'
services:
  psps:
    image: "factsmission/psps:file-storage"
    ports:
     - "5000:5000"
    environment:
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      RENDERER_LIST: "'https://rdf2h.github.io/renderers/0.0.1/fallback-renderers.ttl' '/renderers'"
    depends_on:
      - "fuseki"
  fuseki:
    image: "linkedsolutions/fuseki"
    environment:
      ADMIN_PASSWORD: "pw123"