version: '3'
services:
  psps:
    build: .
    image: factsmission/psps
    ports:
     - "5000:5000"
    environment:
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      WEBHOOK_SECRET: "${WEBHOOK_SECRET}"
      RENDERER_LIST: "'https://rdf2h.github.io/renderers/0.0.3/fallback-renderers.ttl' '/renderers'"
    depends_on:
      - "fuseki"
  fuseki:
    image: "linkedsolutions/fuseki"
    environment:
      ADMIN_PASSWORD: "pw123"
